pipeline {
    agent any

    stages {

        stage("Setup Environment") {
            steps {
                echo "Creating Python virtual environment and installing Robot Framework..."
                sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install robotframework
                """
            }
        }

        stage("Run Robot Tests") {
            steps {
                echo "Running Robot Framework tests..."
                sh """
                    . venv/bin/activate
                    robot -d results automation/ItineraLogin.robot
                """
            }
        }

        stage("Publish Results") {
            steps {
                echo "Publishing Robot Framework results..."
                archiveArtifacts artifacts: 'results/**', fingerprint: true
            }
        }
    }

    post {
        always { echo "Pipeline finished." }
        success { echo "All tests passed!" }
        failure { echo "Some tests failed." }
    }
}