pipeline {
    agent any

    parameters {
        string(name: 'BASE_URL', defaultValue: 'https://theitinera.app', description: 'Frontend URL to test')
    }

    stages {
        stage("Clean Workspace") {
            steps {
                echo "Cleaning workspace..."
                deleteDir()
            }
        }

        stage("Setup Environment") {
            steps {
                echo "Setting up Python environment..."
                sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install robotframework
                    pip install -r requirements.txt || true
                """
            }
        }

        stage("Run Robot Tests for Itinera ") {
            steps {
                echo "Running Robot Framework tests..."
                sh """
                    . venv/bin/activate
                    robot -d results automation/ItineraLogin.robot
                """
            }
        }

        stage("Publish Results") {
            steps {
                archiveArtifacts artifacts: 'results/**', fingerprint: true
            }
        }
    }

    post {
        always { echo "Pipeline finished." }
        success { echo "All tests passed!" }
        failure { echo "Some tests failed." }
    }
}